spring:
  application:
    name: geulnamu-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  jwt:
    accessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
    refreshTokenKey: ${JWT_REFRESH_TOKEN_KEY}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}

# (선택) 콘솔 접속 보안·Actuator 연동
management:
  endpoints:
    web:
      exposure:
        include: health,info,metics,hikaricp
  metrics:
    enable:
      hikari: true

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true