spring:
  datasource:
    # 메모리 모드: jdbc:h2:mem:testdb
    # 파일 모드:   jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # 스키마 생성·변경 전략(create, create-drop, update, validate 등)
      ddl-auto: create  # update
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true       # 웹 콘솔 활성화
      path: /h2-console  # 접속 URL (기본값: /h2-console)

# (선택) 콘솔 접속 보안·Actuator 연동
management:
  endpoints:
    web:
      exposure:
        include: health,info,h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE