// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZl2WCbE8GdzPaXY6DHgfV-f2qNpEvPw',
    appId: '1:576790553336:web:332b81d5870d4a4d04910d',
    messagingSenderId: '576790553336',
    projectId: 'geulnamu-app',
    authDomain: 'geulnamu-app.firebaseapp.com',
    storageBucket: 'geulnamu-app.firebasestorage.app',
    measurementId: 'G-DD1ESVQNED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbVM_t_CMINDcIhNixBsTkcFGmOqJTx_g',
    appId: '1:576790553336:android:7722c4be1a8d6aec04910d',
    messagingSenderId: '576790553336',
    projectId: 'geulnamu-app',
    storageBucket: 'geulnamu-app.firebasestorage.app',
  );
}
